Revert "Add new aconfig dependencies"
This reverts commit ceedc5da7769a461d72b6e8d4aa022834e9a822b.

FAILED: /out/soong/build.voltage_lemonade.ninja
cd "$(dirname "/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/out/soong"     --out "/out"     --soong_variables /out/soong/soong.voltage_lemonade.variables -o /out/soong/build.voltage_lemonade.ninja --globListDir voltage_lemonade --globFile /out/soong/globs-voltage_lemonade.ninja -l /out/.module_paths/Android.bp.list --available_env /out/soong/soong.environment.available --used_env /out/soong/soong.environment.used.voltage_lemonade.build Android.bp
error: frameworks/av/services/audiopolicy/tests/Android.bp:11:1: "audiopolicy_tests" depends on undefined module "aconfig_lib_cc_shared_link.defaults".
Or did you mean ["aconfig_lib_cc_static_link.defaults" "config-com.android.tv.feedbackconsent"]?
fatal errors encountered
23:43:37 soong bootstrap failed with: exit status 1

Change-Id: a806feab49c3d31728acdaba56708fcecd9564de
Signed-off-by: TogoFire <togofire@mailfence.com>