Revert "Define vintf_fragments as modules"
This reverts commit 1e375ba3c7f581c687caaa207a0468befeed8bdb.

Log:
FAILED: /out/soong/build.voltage_lemonade.ninja
cd "$(dirname "/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/out/soong"     --out "/out"     --soong_variables /out/soong/soong.voltage_lemonade.variables -o /out/soong/build.voltage_lemonade.ninja --globListDir voltage_lemonade --globFile /out/soong/globs-voltage_lemonade.ninja -l /out/.module_paths/Android.bp.list --available_env /out/soong/soong.environment.available --used_env /out/soong/soong.environment.used.voltage_lemonade.build Android.bp
error: frameworks/av/drm/mediadrm/plugins/clearkey/aidl/Android.bp:89:27: unrecognized property "vintf_fragment_modules"
error: frameworks/av/drm/mediadrm/plugins/clearkey/aidl/Android.bp:101:27: unrecognized property "vintf_fragment_modules"
error: frameworks/av/drm/mediadrm/plugins/clearkey/aidl/Android.bp:104:1: unrecognized module type "vintf_fragment"
fatal errors encountered

Change-Id: 88a23ece8e4a7abbf9a728151998f413b66de7b4
Signed-off-by: TogoFire <togofire@mailfence.com>