Revert "StagefrightRecoder: Use flag to enable or disable b-frame"
This reverts commit f5a01fa5332fc8d1fef3d7dc2c42ba5237bc6bae.

FAILED: /out/soong/build.voltage_lemonade.ninja
cd "$(dirname "/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/out/soong"     --out "/out"     --soong_variables /out/soong/soong.voltage_lemonade.variables -o /out/soong/build.voltage_lemonade.ninja --globListDir voltage_lemonade --globFile /out/soong/globs-voltage_lemonade.ninja -l /out/.module_paths/Android.bp.list --available_env /out/soong/soong.environment.available --used_env /out/soong/soong.environment.used.voltage_lemonade.build Android.bp
error: frameworks/av/media/libstagefright/writer_fuzzers/Android.bp:20:1: "//frameworks/av/media/libstagefright/writer_fuzzers" depends on undefined module "trendy_team_android_media_solutions_editing".
Or did you mean ["aidl_test_loggable_interface-java-generator" "hidl_test_product@2.0-inheritance-hierarchy" "netd_event_listener_interface-V1-cpp-source" "netd_event_listener_interface-V1-ndk-source" "netd_event_listener_interface-V2-cpp-source" "netd_event_listener_interface-V2-ndk-source" "netd_event_listener_interface-V3-cpp-source" "netd_event_listener_interface-V3-ndk-source" "sdk_test_29_com.android.media.remotedisplay" "sdk_test_30_com.android.media.remotedisplay" "sdk_test_31_com.android.media.remotedisplay" "sdk_test_32_com.android.media.remotedisplay" "sdk_test_33_com.android.media.remotedisplay" "sdk_test_34_com.android.media.remotedisplay" "sdk_test_35_com.android.media.remotedisplay"]?
fatal errors encountered
23:52:54 soong bootstrap failed with: exit status 1

Change-Id: 2d88293a891b1d4f3de5072855bfcfd2c35cc558
Signed-off-by: TogoFire <togofire@mailfence.com>