Revert "Upgrade to tuner aidl V3 interface"
This reverts commit a3517116f0dd616825b0d1230dea8654b0feb55a.

FAILED: /out/soong/build.voltage_lemonade.ninja
cd "$(dirname "/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/out/soong"     --out "/out"     --soong_variables /out/soong/soong.voltage_lemonade.variables -o /out/soong/build.voltage_lemonade.ninja --globListDir voltage_lemonade --globFile /out/soong/globs-voltage_lemonade.ninja -l /out/.module_paths/Android.bp.list --available_env /out/soong/soong.environment.available --used_env /out/soong/soong.environment.used.voltage_lemonade.build Android.bp
error: frameworks/av/services/tuner/Android.bp:15:12: module "tv_tuner_aidl_interface_interface": imports: "tv_tuner_aidl_interface" depends on "android.hardware.tv.tuner" version "3"("android.hardware.tv.tuner-V3"), which doesn't exist. The version must be one of ["1" "2"]
fatal errors encountered
23:48:32 soong bootstrap failed with: exit status 1

Change-Id: 94c0da2a4d580bfa9a0e0ee1c08a2b797c4ad079
Signed-off-by: TogoFire <togofire@mailfence.com>