Revert "Sync with new drm common aidl interface"
This reverts commit 2e55e1f2aef3cd0d5dcc1af349b28d1a4b82c7cc.

FAILED: /out/soong/build.voltage_lemonade.ninja
cd "$(dirname "/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/out/soong"     --out "/out"     --soong_variables /out/soong/soong.voltage_lemonade.variables -o /out/soong/build.voltage_lemonade.ninja --globListDir voltage_lemonade --globFile /out/soong/globs-voltage_lemonade.ninja -l /out/.module_paths/Android.bp.list --available_env /out/soong/soong.environment.available --used_env /out/soong/soong.environment.used.voltage_lemonade.build Android.bp
Warning: Module 'androidx.wear_wear' depends on non-existing optional_uses_libs 'wear-sdk'
Warning: Module 'androidx.wear.compose_compose-foundation' depends on non-existing optional_uses_libs 'wear-sdk'
error: frameworks/av/drm/libmediadrmrkp/Android.bp:1:1: "libmediadrmrkp" depends on undefined module "android.hardware.drm.common-V1-ndk".
Or did you mean ["android.hardware.audio.common-V1-ndk" "android.hardware.common-V1-ndk" "android.hardware.wifi.common-V1-ndk"]?
fatal errors encountered

Change-Id: 36dfa8b6167911462ec1a271a34ad99b343649fa
Signed-off-by: TogoFire <togofire@mailfence.com>