Revert "Migrate forced config and force use to android.media.audio.common.types"
This reverts commit 873738c761c34b56c018783455d908af1edf0605.

FAILED: /out/soong/.intermediates/frameworks/av/media/libaudioclient/audiopolicy-aidl-java-source/gen/android/media/IAudioPolicyService.java
/out/host/linux-x86/bin/aidl --lang=java -Weverything -Wno-missing-permission-annotation --min_sdk_version current -p/out/soong/.intermediates/system/hardware/interfaces/media/android.media.audio.common.types_interface/3/preprocessed.aidl -p/out/soong/.intermediates/frameworks/av/audio-permission-aidl_interface/preprocessed.aidl -p/out/soong/.intermediates/frameworks/av/media/libaudioclient/audioclient-types-aidl_interface/preprocessed.aidl -p/out/soong/.intermediates/frameworks/av/media/libaudioclient/audiopolicy-types-aidl_interface/preprocessed.aidl -p/out/soong/.intermediates/frameworks/av/media/libaudioclient/capture_state_listener-aidl_interface/preprocessed.aidl -p/out/soong/.intermediates/frameworks/native/libs/permission/framework-permission-aidl_interface/preprocessed.aidl -p/out/soong/.intermediates/frameworks/av/media/libaudioclient/spatializer-aidl_interface/preprocessed.aidl --ninja -d /out/soong/.intermediates/frameworks/av/media/libaudioclient/audiopolicy-aidl-java-source/gen/android/media/IAudioPolicyService.java.d -o /out/soong/.intermediates/frameworks/av/media/libaudioclient/audiopolicy-aidl-java-source/gen  -Nframeworks/av/media/libaudioclient/aidl frameworks/av/media/libaudioclient/aidl/android/media/IAudioPolicyService.aidl
ERROR: frameworks/av/media/libaudioclient/aidl/android/media/IAudioPolicyService.aidl: Couldn't find import for class android.media.audio.common.AudioPolicyForcedConfig. Searched here:
 - frameworks/av/media/libaudioclient/aidl/
ERROR: frameworks/av/media/libaudioclient/aidl/android/media/IAudioPolicyService.aidl: Couldn't find import for class android.media.audio.common.AudioPolicyForceUse. Searched here:
 - frameworks/av/media/libaudioclient/aidl/
00:07:44 ninja failed with: exit status 1

Change-Id: 5c2c167a0f605b11497debc795c69e9642b3ef42
Signed-off-by: TogoFire <togofire@mailfence.com>