Revert "Add new aconfig dependencies"
This reverts commit 7f48bda6b006f7f443b39eab5764b522d1e5bbe7.

Log:
FAILED: /out/soong/build.voltage_lemonade.ninja
cd "$(dirname  /out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename  /out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out  /out/soong"     --out  /out"     --soong_variables /out/soong/soong.voltage_lemonade.variables -o /out/soong/build.voltage_lemonade.ninja --globListDir voltage_lemonade --globFile /out/soong/globs-voltage_lemonade.ninja -l /out/.module_paths/Android.bp.list --available_env /out/soong/soong.environment.available --used_env /out/soong/soong.environment.used.voltage_lemonade.build Android.bp
error: frameworks/av/services/mediaresourcemanager/test/Android.bp:11:1: "ResourceManagerService_test" depends on undefined module "aconfig_lib_cc_shared_link.defaults".
Or did you mean ["aconfig_lib_cc_static_link.defaults" "config-com.android.tv.feedbackconsent"]?
error: frameworks/av/services/mediaresourcemanager/test/Android.bp:65:1: "ResourceObserverService_test" depends on undefined module "aconfig_lib_cc_shared_link.defaults".
Or did you mean ["aconfig_lib_cc_static_link.defaults" "config-com.android.tv.feedbackconsent"]?
fatal errors encountered
23:39:58 soong bootstrap failed with: exit status 1

Change-Id: 2c33aa4327de8ba2b1ec8515697b226dae4c2736
Signed-off-by: TogoFire <togofire@mailfence.com>